# Generated by Django 3.2.3 on 2021-05-31 20:53

from django.db import migrations, models
import django.db.models.deletion
import newsletter.storages


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(storage=newsletter.storages.OverwriteStorage(), upload_to=newsletter.storages.upload_to, verbose_name='Image')),
                ('news_letter', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='newsletter.newsletter')),
            ],
        ),
    ]
