# Generated by Django 3.2.3 on 2021-06-01 06:11

import django.core.files.storage
from django.db import migrations, models
import newsletter.models
import newsletter.storages


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_1', models.ImageField(storage=django.core.files.storage.FileSystemStorage(base_url='/uploads', location='/Users/llamasramirez'), upload_to=newsletter.storages.upload_to_image_1)),
                ('image_2', models.ImageField(blank=True, null=True, storage=newsletter.storages.OverwriteStorage(), upload_to=newsletter.models.Newsletter.upload_to_image_2)),
                ('image_3', models.ImageField(blank=True, null=True, storage=newsletter.storages.OverwriteStorage(), upload_to=newsletter.models.Newsletter.upload_to_image_3)),
                ('image_4', models.ImageField(blank=True, null=True, storage=newsletter.storages.OverwriteStorage(), upload_to=newsletter.models.Newsletter.upload_to_image_4)),
            ],
        ),
    ]
